### ISSUE TITLE
New provider: Enmax (Canada)

### ISSUE THREAD

**Issue by pironic** [tronikos/opower#17]
Good afternoon, I'm super eager to use this library (as part of home-assistant) but my python abilities are lacking. If I can provide all of the information from a browser session to login is there someone that can help add/validate the new provider? I'd be happy to assist in any-way that I can. 

the subdomain that I see the requests going through are at enmx.opower.com (the missing a is intentional) and the authenticate urls are also mentioning the sso at sso.enmax.com.

When I log into my provider's website at enmax.com I am never presented with a url in my browser visible at opower.com but i see many hits to the enmx.opower.com api in the network tab of chrome's dev tools.

**Comment by tronikos** [comment]
My recommendation is to try to find someone in your region that has Enmax and has some basic python skills. The login seems easy. It just sends a post request to `https://www.enmax.com/SignInSite/_vti_bin/Enmax.Internet.Auth/AuthService.svc/AuthenticateUser` with payload: `{email: "test@test.com", password: "test", queryString: "", autoUnlockIntervalMinutes: 15}`
Once you login there should be some other request that returns the opower access token.
The code in the other utilities should be very helpful to use as example.

Since this will be the first non US utility, there are some additional changes needed since https://github.com/home-assistant/core/blob/dev/homeassistant/components/opower/sensor.py uses USD as the unit for the cost entities.

**Comment by aman207** [comment]
Hi. I've created a PR for this. 

HA automatically set the correct currency in the Energy dashboard at least. Not sure if this is because my localization settings are set to Canada?

![image](https://github.com/tronikos/opower/assets/3377153/abf31081-c97b-4003-a4c7-0dc651476813)

**Comment by tronikos** [comment]
I don't remember setting a unit for the statistics so I guess it makes sense the energy dashboard to work. How about the forecast and usage sensors?

**Comment by aman207** [comment]
Hmm, actually there doesn't appear to be any sensors at all...

I see this in the logs

```
2023-09-13 01:16:05.388 DEBUG (MainThread) [homeassistant.components.opower.coordinator] Updating sensor data with: []
2023-09-13 01:16:05.388 DEBUG (MainThread) [homeassistant.components.opower.coordinator] Updating Statistics for opower:enmx_elec_0020002707151_energy_cost and opower:enmx_elec_0020002707151_energy_consumption
2023-09-13 01:16:05.573 DEBUG (MainThread) [homeassistant.components.opower.coordinator] Finished fetching Opower data in 4.792 seconds (success: True)
2023-09-13 01:16:05.576 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.opower
```

**Comment by tronikos** [comment]
Not all utilities support the forecast API. I guess we can delay fixing the sensors unit then.
