### ISSUE TITLE
ConEd unable to authenticate after backup/restore

### ISSUE THREAD

**Issue by mt98987987** [tronikos/opower#50]
I am attempting to add my ConEd account after having to revert to an old backup for an unrelated Zwave issue. When I try to setup I add my username and password and then enter my OTP secret. I get an error saying "Invalid authentication". I have tried the credentials on a clean install and it works perfectly. I don't see anything in the log but I am not sure where to look to troubleshoot this further.

**Comment by tronikos** [comment]
This should had been filed in https://github.com/home-assistant/core
Make sure you use the latest Home Assistant build since there was a ConEd fix in 2023.10.4
I have PG&E and I've been successful in the past restoring an old backup.
If it works on a clean install, try removing and re-adding the integration.
